### ISSUE TITLE
can't start waydroid session

### ISSUE THREAD

**Issue by krrrak** [eupnea-linux/chromeos-kernel#4]
system:archlinux
Fail starting waydroid session with this kernel, while using mainline kernel, system get frozen when starting waydroid session.
And when system installing 'anbox-modules-dkms-git' that provides the kernel modules that waydroid needs, it report error when installing binder module for chromeos kernel.

**Comment by Apacelus** [comment]
Both the mainline and chromeos kernels have all modules needed for waydroid support

**Comment by krrrak** [comment]
I run 'waydroid show-full-ui' in console.
It failed just like this:
[]Starting waydroid session
[]RuntimeError; Command failed: % /usr/lib/waydroid/data/seripts/waydrod-net.sh start

**Comment by Apacelus** [comment]
1. Thats not a full error log and I cant do anything with it
2. I have successfully ran waydroid on Fedora Depthboot before, so it is not a kernel issue. I suggest you open an issue on the waydroid repo and provide a full log. Then come back here if the waydroid devs tell you to do so
